#include <TThread.h>
#include <TROOT.h>
#include <TApplication.h>
#include <TVirtualX.h>
#include <TVirtualPadEditor.h>
#include <TGResourcePool.h>
#include <TGListBox.h>
#include <TGListTree.h>
#include <TGFSContainer.h>
#include <TGClient.h>
#include <TGFrame.h>
#include <TGIcon.h>
#include <TGLabel.h>
#include <TGButton.h>
#include <TGTextEntry.h>
#include <TGNumberEntry.h>
#include <TGMsgBox.h>
#include <TGMenu.h>
#include <TGCanvas.h>
#include <TGComboBox.h>
#include <TGTab.h>
#include <TGSlider.h>
#include <TGDoubleSlider.h>
#include <TGFileDialog.h>
#include <TGTextEdit.h>
#include <TGShutter.h>
#include <TGProgressBar.h>
#include <TGColorSelect.h>
#include <TRootEmbeddedCanvas.h>
#include <TCanvas.h>
#include <TColor.h>
#include <TH1.h>
#include <TH2.h>
#include <TRandom.h>
#include <TSystem.h>
#include <TSystemDirectory.h>
#include <TEnv.h>
#include <TFile.h>
#include <TKey.h>
#include <TGDockableFrame.h>
#include <TGFontDialog.h>
#include <TGenericClassInfo.h>
#include <TRootEmbeddedCanvas.h>
#include <TF1.h>
#include <TGXYLayout.h>
#include <TGTable.h>
#include <TGStatusBar.h>
#include "TGButtonGroup.h"
#include <TTree.h>
#include <TGTab.h>
#include <TGraph.h>
#include "TMultiGraph.h"
#include "TGTripleSlider.h"
#include <TStyle.h>
#include "TGLayout.h"
#include "TMath.h"

#include <TPave.h>
#include <TPaveText.h>

#include "TLatex.h"